### ISSUE TITLE
Issues with React 0.14.0-rc1

### ISSUE THREAD

**Issue by approots** [furqanZafar/react-selectize#2]
![selectize_dom_errors](https://cloud.githubusercontent.com/assets/235342/9979442/c18c807e-5f21-11e5-9c27-b5d187cbc49e.png)

The warnings above apprear when using `React.render(...)`. If I use `ReactDOM.render(...)`, then the following error appears:

![selectize_dom_error](https://cloud.githubusercontent.com/assets/235342/9979452/72047ace-5f22-11e5-9752-4d7eb4b45a28.png)

**Comment by furqanZafar** [comment]
It is difficult to completely support multiple versions of React at the same sime, especially in this case since completely supporting `0.14.x-rc*` versions will break support for the current stable `0.13.3` release. 

However, release `0.2.1` should fix the error regarding `addComponentAsRefTo..` and also reduce the number of warnings regarding `getDOMNode` while maintaining support for React `0.13.3`

**Comment by furqanZafar** [comment]
the current version, 0.3.0, uses React 0.14.0

**Comment by ruscoder** [comment]
@furqanZafar in version 0.3.5 i have same bug, in 0.3.0 all is okay
