### ISSUE TITLE
Select elements can not be used in forms

### ISSUE THREAD

**Issue by marchbnr** [furqanZafar/react-selectize#26]
The features claim "Drop in replacement for React.DOM.Select".

However, it can not be used in forms, to submit the select's value?!

**Comment by furqanZafar** [comment]
Please elaborate, a code snippet would be helpful, thanks.

**Comment by marchbnr** [comment]
In the following code, the react select element works like the html equivalent: https://jsfiddle.net/reactjs/69z2wepo/

If you look at the parameters of the get request you can see that the value of the select field has been submitted.

Shouldn't react-selectize behave like an ordinary select input, or am I missing something here?

**Comment by furqanZafar** [comment]
added form serialisation support in 0.5.3, you must specify the name prop in order to use it,
by default the it uses the value prop of the item as the value for GET / POST request, but you can override this by specifying a serialize prop:
`serialize: function(item){ return !!item ? item.value : undefined }`
