### ISSUE TITLE
Delay filtering for 1000++ items in dropdown?

### ISSUE THREAD

**Issue by annelorraineuy** [furqanZafar/react-selectize#48]
Hi there. Thanks so much for this! I love it! Just wanna know though if it's possible to delay the filtering? I have a dropdown of at least 1000 items and the filtering really lags the component. Is there a way for me to just set it to search after maybe 2 seconds or so?

**Comment by furqanZafar** [comment]
Here are a couple of things you can do to improve the performance:

1. Implement `uid` prop, for example, `uid: (item) => item.value` it receives an Item as the first argument and must return something that is unique about that item in the list (such as the value property)

2. Implement the `filterOptions` prop to return only the top n search results instead of displaying all 1000, for example:
```
filterOptions: (options, search) => {
 const normalizedSearch = search.toLowerCase().trim() 
 return _.take(options.filter((item) => {
  return item.label.toLowerCase().trim().indexOf(normalizedSearch) != -1
 }), 100)
}
```

3. Delay filtering using `underscore` `debounce`

this pen summarizes these techniques: http://codepen.io/furqanZafar/pen/KzpqqM
