### ISSUE TITLE
Animating the dropdown?

### ISSUE THREAD

**Issue by chen-ye** [furqanZafar/react-selectize#5]
Relatively new to react - would properly animating the dropdown opening and closing require modifying the component itself?

**Comment by furqanZafar** [comment]
I haven't really given the matter much thought before, but yea i guess it would require modifying the component, since the dropdown element does not exist till you focus or click on the select control. 

Will try to implement this in the next update: https://facebook.github.io/react/docs/animation.html

**Comment by chen-ye** [comment]
Excellent, thank you!
I'm a big fan of the behavior in http://jquense.github.io/react-widgets/docs/#/multiselect (though just a suggestion ofc)

**Comment by furqanZafar** [comment]
added dropdown animation in 0.3.3
(http://furqanzafar.github.io/react-selectize/#/?category=multi&example=animated-dropdown)
