### ISSUE TITLE
Tab should auto-complete

### ISSUE THREAD

**Issue by marchbnr** [furqanZafar/react-selectize#53]
If some text was entered in a select element, tab should not change the focus but try to auto-complete the written text

**Comment by furqanZafar** [comment]
you can do that by using tab as a delimiter i.e:
```javascript
delimiters = {[9]}
```
use `cancelKeyboardEventOnSelection` prop to keep / prevent the default behaviour of the `tab` key
http://codepen.io/furqanZafar/pen/VaPvQw

**Comment by marchbnr** [comment]
Yes it works for a SimpleSelect, but in a MultiSelect hitting tab will always auto-complete if the dropdown is displayed. Even if no text was entered, although you would expect, that the focus is switched if you have not entered any text.

**Comment by furqanZafar** [comment]
you can do that using `firstOptionIndexToHighlight` prop:

the following tells selectize to highlight the first option only if the search field is not empty, this way when you press the tab key the focus is shifted to the next control instead of selecting an option (since nothing is highlighted)
```javascript
      firstOptionIndexToHighlight = {(optionIndex, options, value, search) => {
        return (optionIndex == 0 && search.length == 0) ? -1 : optionIndex
      }}
```
for example, http://codepen.io/furqanZafar/pen/PNqoOY?editors=0010
