### ISSUE TITLE
react 15 - update dependency

### ISSUE THREAD

**Issue by babsonmatt** [furqanZafar/react-selectize#68]
Can we update the react dependency to v15?

**Comment by gsanta** [comment]
I see that in the package.json you accept both v14 and v15 of react.
But somehow I could not make it work with my project where I use v14.
I had a lot of peerDependency issues, that I dd not fully understand, since your package.json tells that it should work with v14.

My suspicion is that react v15 brings some other packages which need v15, namely:
npm info postinstall react-addons-css-transition-group@15.0.1
npm info postinstall react-addons-shallow-compare@15.0.1

Do you have any suggestion for this issue?
Or everybody should update to v15? :)

**Comment by furqanZafar** [comment]
I tested version 2.0.1, with react@0.14.0, seems to be working fine:
my dependencies object in package.json:
```
{
  "dependencies": {
    "react": "^0.14.0",
    "react-addons-css-transition-group": "^0.14.0",
    "react-addons-shallow-compare": "^0.14.0",
    "react-dom": "^0.14.0",
    "react-selectize": "^2.0.1"
  }
}
```
index.js file:
```javascript
import React from "react"
import ReactDOM from "react-dom"
import ReactSelectize from "react-selectize"

class App extends React.Component {

    constructor(props) {
        super(props)
    }

    render() {
        return (
            <ReactSelectize.SimpleSelect
                placeholder = "Select a fruit"
                options = {["apple", "mango", "grapes", "banana"].map ((fruit) => {
                    return {label: fruit, value: fruit}
                })}
            />
        )
    }
}

ReactDOM.render(<App/>, document.getElementById("mount-node"))
```

**Comment by gsanta** [comment]
You are right!
For me the problem was that I did not explicitly set the  react-addons-css-transition-group and react-addons-shallow-compare versions in my package.json, and react-selectize pulled down v15 by default.

But setting them explicitly to v14 solves the problem.

Thank you!

**Comment by DanielRuf** [comment]
Any plans top update this dependency? Would be great to have it in the upstream version.

**Comment by yurir** [comment]
yep, 15..3.1 would be great.
